///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FarmersListModelData {
/*
{
  "supplier_name": "ABHAY PURANDAR KHOT ",
  "village": "BEDKIHAL",
  "name": "FA-1"
} 
*/

  String? supplierName;
  String? village;
  String? name;

  FarmersListModelData({
    this.supplierName,
    this.village,
    this.name,
  });
  FarmersListModelData.fromJson(Map<String, dynamic> json) {
    supplierName = json['supplier_name']?.toString();
    village = json['village']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['supplier_name'] = supplierName;
    data['village'] = village;
    data['name'] = name;
    return data;
  }
}

class FarmersListModel {
/*
{
  "data": [
    {
      "supplier_name": "ABHAY PURANDAR KHOT ",
      "village": "BEDKIHAL",
      "name": "FA-1"
    }
  ]
} 
*/

  List<FarmersListModelData?>? data;

  FarmersListModel({
    this.data,
  });
  FarmersListModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <FarmersListModelData>[];
      v.forEach((v) {
        arr0.add(FarmersListModelData.fromJson(v));
      });
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    return data;
  }
}
